package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Branches generated by hbm2java
 */
@Entity
@Table(name = "Branches", schema = "public"
)
public class Branches implements java.io.Serializable {

    private int id;
    private City city;
    private Status status;
    private String numar;
    private String adress;
    private String name;
    private String cordonate;
    private Set<Accounts> accountses = new HashSet<>(0);

    public Branches() {
    }

    public Branches(int id) {
        this.id = id;
    }

    public Branches(int id, City city, Status status, String numar, String adress, String name, String cordonate, Set<Accounts> accountses) {
        this.id = id;
        this.city = city;
        this.status = status;
        this.numar = numar;
        this.adress = adress;
        this.name = name;
        this.cordonate = cordonate;
        this.accountses = accountses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cityId")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusId")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "numar", length = 50)
    public String getNumar() {
        return this.numar;
    }

    public void setNumar(String numar) {
        this.numar = numar;
    }

    @Column(name = "adress", length = 50)
    public String getAdress() {
        return this.adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "cordonate", length = 50)
    public String getCordonate() {
        return this.cordonate;
    }

    public void setCordonate(String cordonate) {
        this.cordonate = cordonate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "branches")
    public Set<Accounts> getAccountses() {
        return this.accountses;
    }

    public void setAccountses(Set<Accounts> accountses) {
        this.accountses = accountses;
    }

}
