package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cards generated by hbm2java
 */
@Entity
@Table(name = "Cards", schema = "public"
)
public class Cards implements java.io.Serializable {

    private long id;
    private Accounts accounts;
    private Status status;
    private Types types;
    private String pan;
    private Date dataExpiration;
    private String description;
    private String detaily;
    private Date openDate;

    public Cards() {
    }

    public Cards(long id) {
        this.id = id;
    }

    public Cards(long id, Accounts accounts, Status status, Types types, String pan, Date dataExpiration, String description, String detaily, Date openDate) {
        this.id = id;
        this.accounts = accounts;
        this.status = status;
        this.types = types;
        this.pan = pan;
        this.dataExpiration = dataExpiration;
        this.description = description;
        this.detaily = detaily;
        this.openDate = openDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "accuntId")
    public Accounts getAccounts() {
        return this.accounts;
    }

    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusId")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "typeId")
    public Types getTypes() {
        return this.types;
    }

    public void setTypes(Types types) {
        this.types = types;
    }

    @Column(name = "pan", length = 50)
    public String getPan() {
        return this.pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dataExpiration", length = 23)
    public Date getDataExpiration() {
        return this.dataExpiration;
    }

    public void setDataExpiration(Date dataExpiration) {
        this.dataExpiration = dataExpiration;
    }

    @Column(name = "description", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "detaily", length = 100)
    public String getDetaily() {
        return this.detaily;
    }

    public void setDetaily(String detaily) {
        this.detaily = detaily;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "openDate", length = 23)
    public Date getOpenDate() {
        return this.openDate;
    }

    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

}
