package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "City", schema = "public"
)
public class City implements java.io.Serializable {

    private int id;
    private String name;
    private String alias;
    private String description;
    private String location;
    private String shortName;
    private Set<Branches> brancheses = new HashSet<>(0);
    private Set<Customers> customerses = new HashSet<>(0);
    private Set<Terminals> terminalses = new HashSet<>(0);

    public City() {
    }

    public City(int id) {
        this.id = id;
    }

    public City(int id, String name, String alias, String description, String location, String shortName, Set<Branches> brancheses, Set<Customers> customerses, Set<Terminals> terminalses) {
        this.id = id;
        this.name = name;
        this.alias = alias;
        this.description = description;
        this.location = location;
        this.shortName = shortName;
        this.brancheses = brancheses;
        this.customerses = customerses;
        this.terminalses = terminalses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "alias", length = 100)
    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    @Column(name = "description", length = 500)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "location", length = 50)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "shortName", length = 20)
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    public Set<Branches> getBrancheses() {
        return this.brancheses;
    }

    public void setBrancheses(Set<Branches> brancheses) {
        this.brancheses = brancheses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }

    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
    public Set<Terminals> getTerminalses() {
        return this.terminalses;
    }

    public void setTerminalses(Set<Terminals> terminalses) {
        this.terminalses = terminalses;
    }

}
