package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Devices generated by hbm2java
 */
@Entity
@Table(name = "Devices", schema = "public"
)
public class Devices implements java.io.Serializable {

    private long id;
    private NetworkOperatorManufacturer networkOperatorManufacturer;
    private String macAdress;
    private String imie;
    private String imsi;
    private Set<WrongPassword> wrongPasswords = new HashSet<>(0);
    private Set<SingInOutSessions> singInOutSessionses = new HashSet<>(0);

    public Devices() {
    }

    public Devices(long id) {
        this.id = id;
    }

    public Devices(long id, NetworkOperatorManufacturer networkOperatorManufacturer, String macAdress, String imie, String imsi, Set<WrongPassword> wrongPasswords, Set<SingInOutSessions> singInOutSessionses) {
        this.id = id;
        this.networkOperatorManufacturer = networkOperatorManufacturer;
        this.macAdress = macAdress;
        this.imie = imie;
        this.imsi = imsi;
        this.wrongPasswords = wrongPasswords;
        this.singInOutSessionses = singInOutSessionses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "networkOperationManufacturerId")
    public NetworkOperatorManufacturer getNetworkOperatorManufacturer() {
        return this.networkOperatorManufacturer;
    }

    public void setNetworkOperatorManufacturer(NetworkOperatorManufacturer networkOperatorManufacturer) {
        this.networkOperatorManufacturer = networkOperatorManufacturer;
    }

    @Column(name = "macAdress")
    public String getMacAdress() {
        return this.macAdress;
    }

    public void setMacAdress(String macAdress) {
        this.macAdress = macAdress;
    }

    @Column(name = "IMIE")
    public String getImie() {
        return this.imie;
    }

    public void setImie(String imie) {
        this.imie = imie;
    }

    @Column(name = "IMSI")
    public String getImsi() {
        return this.imsi;
    }

    public void setImsi(String imsi) {
        this.imsi = imsi;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "devices")
    public Set<WrongPassword> getWrongPasswords() {
        return this.wrongPasswords;
    }

    public void setWrongPasswords(Set<WrongPassword> wrongPasswords) {
        this.wrongPasswords = wrongPasswords;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "devices")
    public Set<SingInOutSessions> getSingInOutSessionses() {
        return this.singInOutSessionses;
    }

    public void setSingInOutSessionses(Set<SingInOutSessions> singInOutSessionses) {
        this.singInOutSessionses = singInOutSessionses;
    }

}
