package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExchangeRate generated by hbm2java
 */
@Entity
@Table(name = "ExchangeRate", schema = "dbo", catalog = "iBancRM"
)
public class ExchangeRate implements java.io.Serializable {

    private long id;
    private Valuta valuta;
    private Date dataIns;
    private BigDecimal officialCurs;
    private BigDecimal buyCurs;
    private BigDecimal sellCurs;

    public ExchangeRate() {
    }

    public ExchangeRate(long id) {
        this.id = id;
    }

    public ExchangeRate(long id, Valuta valuta, Date dataIns, BigDecimal officialCurs, BigDecimal buyCurs, BigDecimal sellCurs) {
        this.id = id;
        this.valuta = valuta;
        this.dataIns = dataIns;
        this.officialCurs = officialCurs;
        this.buyCurs = buyCurs;
        this.sellCurs = sellCurs;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "valutaId")
    public Valuta getValuta() {
        return this.valuta;
    }

    public void setValuta(Valuta valuta) {
        this.valuta = valuta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dataIns", length = 10)
    public Date getDataIns() {
        return this.dataIns;
    }

    public void setDataIns(Date dataIns) {
        this.dataIns = dataIns;
    }

    @Column(name = "officialCurs", scale = 4)
    public BigDecimal getOfficialCurs() {
        return this.officialCurs;
    }

    public void setOfficialCurs(BigDecimal officialCurs) {
        this.officialCurs = officialCurs;
    }

    @Column(name = "buyCurs", scale = 4)
    public BigDecimal getBuyCurs() {
        return this.buyCurs;
    }

    public void setBuyCurs(BigDecimal buyCurs) {
        this.buyCurs = buyCurs;
    }

    @Column(name = "sellCurs", scale = 4)
    public BigDecimal getSellCurs() {
        return this.sellCurs;
    }

    public void setSellCurs(BigDecimal sellCurs) {
        this.sellCurs = sellCurs;
    }

}
