package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Languages generated by hbm2java
 */
@Entity
@Table(name = "Languages", schema = "dbo", catalog = "iBancRM"
)
public class Languages implements java.io.Serializable {

    private int id;
    private String shortName;
    private String name;
    private Set<Message> messages = new HashSet<>(0);
    private Set<News> newses = new HashSet<>(0);
    private Set<Services> serviceses = new HashSet<>(0);
    private Set<Customers> customerses = new HashSet<>(0);

    public Languages() {
    }

    public Languages(int id) {
        this.id = id;
    }

    public Languages(int id, String shortName, String name, Set<Message> messages, Set<News> newses, Set<Services> serviceses, Set<Customers> customerses) {
        this.id = id;
        this.shortName = shortName;
        this.name = name;
        this.messages = messages;
        this.newses = newses;
        this.serviceses = serviceses;
        this.customerses = customerses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "shortName", length = 50)
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<Message> getMessages() {
        return this.messages;
    }

    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<News> getNewses() {
        return this.newses;
    }

    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<Services> getServiceses() {
        return this.serviceses;
    }

    public void setServiceses(Set<Services> serviceses) {
        this.serviceses = serviceses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "languages")
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }

    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

}
