/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package md.ibanc.rm.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "Message", schema = "public"
)
public class Message implements java.io.Serializable {

    private long id;
    private Languages languages;
    private TypeMessage typeMessage;
    private Users users;
    private String subject;
    private String content;
    private Date modifiedAt;
    private Date createdAt;
    private Set<SendMessage> sendMessages = new HashSet<>(0);

    public Message() {
    }

    public Message(long id) {
        this.id = id;
    }

    public Message(long id, Languages languages, TypeMessage typeMessage, Users users, String subject, String content, Date modifiedAt, Date createdAt, Set<SendMessage> sendMessages) {
        this.id = id;
        this.languages = languages;
        this.typeMessage = typeMessage;
        this.users = users;
        this.subject = subject;
        this.content = content;
        this.modifiedAt = modifiedAt;
        this.createdAt = createdAt;
        this.sendMessages = sendMessages;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "langId")
    public Languages getLanguages() {
        return this.languages;
    }

    public void setLanguages(Languages languages) {
        this.languages = languages;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "typeId")
    public TypeMessage getTypeMessage() {
        return this.typeMessage;
    }

    public void setTypeMessage(TypeMessage typeMessage) {
        this.typeMessage = typeMessage;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "subject")
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "content")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modifiedAt", length = 23)
    public Date getModifiedAt() {
        return this.modifiedAt;
    }

    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdAt", length = 23)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
    public Set<SendMessage> getSendMessages() {
        return this.sendMessages;
    }

    public void setSendMessages(Set<SendMessage> sendMessages) {
        this.sendMessages = sendMessages;
    }
}
