package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NetworkOperator generated by hbm2java
 */
@Entity
@Table(name = "NetworkOperator", schema = "public"
)
public class NetworkOperator implements java.io.Serializable {

    private int id;
    private String networkOperatorCode;
    private String networkOperatorName;
    private Date createdAt;
    private Set<NetworkOperatorManufacturer> networkOperatorManufacturers = new HashSet<>(0);

    public NetworkOperator() {
    }

    public NetworkOperator(int id) {
        this.id = id;
    }

    public NetworkOperator(int id, String networkOperatorCode, String networkOperatorName, Date createdAt, Set<NetworkOperatorManufacturer> networkOperatorManufacturers) {
        this.id = id;
        this.networkOperatorCode = networkOperatorCode;
        this.networkOperatorName = networkOperatorName;
        this.createdAt = createdAt;
        this.networkOperatorManufacturers = networkOperatorManufacturers;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "networkOperatorCode")
    public String getNetworkOperatorCode() {
        return this.networkOperatorCode;
    }

    public void setNetworkOperatorCode(String networkOperatorCode) {
        this.networkOperatorCode = networkOperatorCode;
    }

    @Column(name = "networkOperatorName")
    public String getNetworkOperatorName() {
        return this.networkOperatorName;
    }

    public void setNetworkOperatorName(String networkOperatorName) {
        this.networkOperatorName = networkOperatorName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdAt", length = 23)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "networkOperator")
    public Set<NetworkOperatorManufacturer> getNetworkOperatorManufacturers() {
        return this.networkOperatorManufacturers;
    }

    public void setNetworkOperatorManufacturers(Set<NetworkOperatorManufacturer> networkOperatorManufacturers) {
        this.networkOperatorManufacturers = networkOperatorManufacturers;
    }

}
