package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NetworkOperatorManufacturer generated by hbm2java
 */
@Entity
@Table(name = "NetworkOperatorManufacturer", schema = "public"
)
public class NetworkOperatorManufacturer implements java.io.Serializable {

    private long id;
    private Manufacturer manufacturer;
    private NetworkOperator networkOperator;
    private Set<Devices> deviceses = new HashSet<>(0);

    public NetworkOperatorManufacturer() {
    }

    public NetworkOperatorManufacturer(long id, Manufacturer manufacturer) {
        this.id = id;
        this.manufacturer = manufacturer;
    }

    public NetworkOperatorManufacturer(long id, Manufacturer manufacturer, NetworkOperator networkOperator, Set<Devices> deviceses) {
        this.id = id;
        this.manufacturer = manufacturer;
        this.networkOperator = networkOperator;
        this.deviceses = deviceses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "manufacturerId", nullable = false)
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "networkOperatorId")
    public NetworkOperator getNetworkOperator() {
        return this.networkOperator;
    }

    public void setNetworkOperator(NetworkOperator networkOperator) {
        this.networkOperator = networkOperator;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "networkOperatorManufacturer")
    public Set<Devices> getDeviceses() {
        return this.deviceses;
    }

    public void setDeviceses(Set<Devices> deviceses) {
        this.deviceses = deviceses;
    }

}
