package md.ibanc.rm.entities;
// Generated Nov 29, 2016 4:52:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NewsCategory generated by hbm2java
 */
@Entity
@Table(name = "NewsCategory", schema = "public"
)
public class NewsCategory implements java.io.Serializable {

    private int id;
    private Languages languages;
    private Status status;
    private Users users;
    private String name;
    private String description;
    private String imagePath;
    private Set<News> newses = new HashSet<News>(0);

    public NewsCategory() {
    }

    public NewsCategory(int id) {
        this.id = id;
    }

    public NewsCategory(int id, Languages languages, Status status, Users users, String name, String description, String imagePath, Set<News> newses) {
        this.id = id;
        this.languages = languages;
        this.status = status;
        this.users = users;
        this.name = name;
        this.description = description;
        this.imagePath = imagePath;
        this.newses = newses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "langId")
    public Languages getLanguages() {
        return this.languages;
    }

    public void setLanguages(Languages languages) {
        this.languages = languages;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusId")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "name", length = 70)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "imagePath", length = 150)
    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "newsCategory")
    public Set<News> getNewses() {
        return this.newses;
    }

    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }

}
