package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "Offer", schema = "dbo", catalog = "iBancRM"
)
public class Offer implements java.io.Serializable {

    private long id;
    private Status status;
    private Users users;
    private String title;
    private String description;
    private Date valabityDate;
    private Date insertDate;
    private Set<LocationOffers> locationOfferses = new HashSet<>(0);

    public Offer() {
    }

    public Offer(long id) {
        this.id = id;
    }

    public Offer(long id, Status status, Users users, String title, String description, Date valabityDate, Date insertDate, Set<LocationOffers> locationOfferses) {
        this.id = id;
        this.status = status;
        this.users = users;
        this.title = title;
        this.description = description;
        this.valabityDate = valabityDate;
        this.insertDate = insertDate;
        this.locationOfferses = locationOfferses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusId")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "title", length = 50)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "valabityDate", length = 23)
    public Date getValabityDate() {
        return this.valabityDate;
    }

    public void setValabityDate(Date valabityDate) {
        this.valabityDate = valabityDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "insertDate", length = 23)
    public Date getInsertDate() {
        return this.insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "offer")
    public Set<LocationOffers> getLocationOfferses() {
        return this.locationOfferses;
    }

    public void setLocationOfferses(Set<LocationOffers> locationOfferses) {
        this.locationOfferses = locationOfferses;
    }

}
