package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name = "Sessions", schema = "public"
)
public class Sessions implements java.io.Serializable {

    private long id;
    private String sessionUid;
    private Date createdAt;
    private Date lastActionAt;
    private Set<SingInOutSessions> singInOutSessionses = new HashSet<SingInOutSessions>(0);
    private Set<CustomerActions> customerActionses = new HashSet<CustomerActions>(0);

    public Sessions() {
    }

    public Sessions(long id) {
        this.id = id;
    }

    public Sessions(long id, String sessionUid, Date createdAt, Date lastActionAt, Set<SingInOutSessions> singInOutSessionses, Set<CustomerActions> customerActionses) {
        this.id = id;
        this.sessionUid = sessionUid;
        this.createdAt = createdAt;
        this.lastActionAt = lastActionAt;
        this.singInOutSessionses = singInOutSessionses;
        this.customerActionses = customerActionses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "sessionUid", length = 36)
    public String getSessionUid() {
        return this.sessionUid;
    }

    public void setSessionUid(String sessionUid) {
        this.sessionUid = sessionUid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createdAt", length = 23)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "lastActionAt", length = 23)
    public Date getLastActionAt() {
        return this.lastActionAt;
    }

    public void setLastActionAt(Date lastActionAt) {
        this.lastActionAt = lastActionAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sessions")
    public Set<SingInOutSessions> getSingInOutSessionses() {
        return this.singInOutSessionses;
    }

    public void setSingInOutSessionses(Set<SingInOutSessions> singInOutSessionses) {
        this.singInOutSessionses = singInOutSessionses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sessions")
    public Set<CustomerActions> getCustomerActionses() {
        return this.customerActionses;
    }

    public void setCustomerActionses(Set<CustomerActions> customerActionses) {
        this.customerActionses = customerActionses;
    }

}
