package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SingInOutSessions generated by hbm2java
 */
@Entity
@Table(name = "SingInOutSessions", schema = "dbo", catalog = "iBancRM"
)
public class SingInOutSessions implements java.io.Serializable {

    private long id;
    private Customers customers;
    private Devices devices;
    private Sessions sessions;
    private Date singInDate;
    private Date singOutDate;
    private String location;
    private String ip;

    public SingInOutSessions() {
    }

    public SingInOutSessions(long id) {
        this.id = id;
    }

    public SingInOutSessions(long id, Customers customers, Devices devices, Sessions sessions, Date singInDate, Date singOutDate, String location, String ip) {
        this.id = id;
        this.customers = customers;
        this.devices = devices;
        this.sessions = sessions;
        this.singInDate = singInDate;
        this.singOutDate = singOutDate;
        this.location = location;
        this.ip = ip;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "customerId")
    public Customers getCustomers() {
        return this.customers;
    }

    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "devicesId")
    public Devices getDevices() {
        return this.devices;
    }

    public void setDevices(Devices devices) {
        this.devices = devices;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sessionId")
    public Sessions getSessions() {
        return this.sessions;
    }

    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "singInDate", length = 23)
    public Date getSingInDate() {
        return this.singInDate;
    }

    public void setSingInDate(Date singInDate) {
        this.singInDate = singInDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "singOutDate", length = 23)
    public Date getSingOutDate() {
        return this.singOutDate;
    }

    public void setSingOutDate(Date singOutDate) {
        this.singOutDate = singOutDate;
    }

    @Column(name = "location", length = 100)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "ip", length = 20)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

}
