package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "Status", schema = "dbo", catalog = "iBancRM"
)
public class Status implements java.io.Serializable {

    private int id;
    private String name;
    private String description;
    private Set<Cards> cardses = new HashSet<>(0);
    private Set<Customers> customerses = new HashSet<>(0);
    private Set<Terminals> terminalses = new HashSet<>(0);
    private Set<Accounts> accountses = new HashSet<>(0);
    private Set<Offer> offers = new HashSet<>(0);
    private Set<Branches> brancheses = new HashSet<>(0);

    public Status() {
    }

    public Status(int id) {
        this.id = id;
    }

    public Status(int id, String name, String description, Set<Cards> cardses, Set<Customers> customerses, Set<Terminals> terminalses, Set<Accounts> accountses, Set<Offer> offers, Set<Branches> brancheses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.cardses = cardses;
        this.customerses = customerses;
        this.terminalses = terminalses;
        this.accountses = accountses;
        this.offers = offers;
        this.brancheses = brancheses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 100)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Cards> getCardses() {
        return this.cardses;
    }

    public void setCardses(Set<Cards> cardses) {
        this.cardses = cardses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }

    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Terminals> getTerminalses() {
        return this.terminalses;
    }

    public void setTerminalses(Set<Terminals> terminalses) {
        this.terminalses = terminalses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Accounts> getAccountses() {
        return this.accountses;
    }

    public void setAccountses(Set<Accounts> accountses) {
        this.accountses = accountses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Offer> getOffers() {
        return this.offers;
    }

    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Branches> getBrancheses() {
        return this.brancheses;
    }

    public void setBrancheses(Set<Branches> brancheses) {
        this.brancheses = brancheses;
    }

}
