package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Terminals generated by hbm2java
 */
@Entity
@Table(name = "Terminals", schema = "dbo", catalog = "iBancRM"
)
public class Terminals implements java.io.Serializable {

    private int id;
    private City city;
    private Status status;
    private TerminalTypes terminalTypes;
    private String name;
    private String description;
    private String adress;
    private String numar;
    private String location;
    private String cordonator;

    public Terminals() {
    }

    public Terminals(int id) {
        this.id = id;
    }

    public Terminals(int id, City city, Status status, TerminalTypes terminalTypes, String name, String description, String adress, String numar, String location, String cordonator) {
        this.id = id;
        this.city = city;
        this.status = status;
        this.terminalTypes = terminalTypes;
        this.name = name;
        this.description = description;
        this.adress = adress;
        this.numar = numar;
        this.location = location;
        this.cordonator = cordonator;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cityId")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "statusId")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "terminalTypeId")
    public TerminalTypes getTerminalTypes() {
        return this.terminalTypes;
    }

    public void setTerminalTypes(TerminalTypes terminalTypes) {
        this.terminalTypes = terminalTypes;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "adress", length = 50)
    public String getAdress() {
        return this.adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }

    @Column(name = "numar", length = 50)
    public String getNumar() {
        return this.numar;
    }

    public void setNumar(String numar) {
        this.numar = numar;
    }

    @Column(name = "location", length = 50)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "cordonator", length = 50)
    public String getCordonator() {
        return this.cordonator;
    }

    public void setCordonator(String cordonator) {
        this.cordonator = cordonator;
    }

}
