package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TerminalTypes generated by hbm2java
 */
@Entity
@Table(name = "TerminalTypes", schema = "public"
)
public class TerminalTypes implements java.io.Serializable {

    private int id;
    private String name;
    private String description;
    private Boolean enable;
    private Date createDate;
    private Set<Terminals> terminalses = new HashSet<Terminals>(0);

    public TerminalTypes() {
    }

    public TerminalTypes(int id) {
        this.id = id;
    }

    public TerminalTypes(int id, String name, String description, Boolean enable, Date createDate, Set<Terminals> terminalses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.enable = enable;
        this.createDate = createDate;
        this.terminalses = terminalses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "enable")
    public Boolean getEnable() {
        return this.enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createDate", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "terminalTypes")
    public Set<Terminals> getTerminalses() {
        return this.terminalses;
    }

    public void setTerminalses(Set<Terminals> terminalses) {
        this.terminalses = terminalses;
    }

}
