package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name = "Types", schema = "public"
)
public class Types implements java.io.Serializable {

    private int id;
    private String name;
    private String description;
    private byte[] img;
    private Set<Cards> cardses = new HashSet<>(0);
    private Set<Accounts> accountses = new HashSet<>(0);

    public Types() {
    }

    public Types(int id) {
        this.id = id;
    }

    public Types(int id, String name, String description, byte[] img, Set<Cards> cardses, Set<Accounts> accountses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.img = img;
        this.cardses = cardses;
        this.accountses = accountses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 50)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "img")
    public byte[] getImg() {
        return this.img;
    }

    public void setImg(byte[] img) {
        this.img = img;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "types")
    public Set<Cards> getCardses() {
        return this.cardses;
    }

    public void setCardses(Set<Cards> cardses) {
        this.cardses = cardses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "types")
    public Set<Accounts> getAccountses() {
        return this.accountses;
    }

    public void setAccountses(Set<Accounts> accountses) {
        this.accountses = accountses;
    }

}
