package md.ibanc.rm.entities;
// Generated Aug 24, 2016 4:57:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Valuta generated by hbm2java
 */
@Entity
@Table(name = "Valuta", schema = "dbo", catalog = "iBancRM"
)
public class Valuta implements java.io.Serializable {

    private int id;
    private String name;
    private String shortName;
    private byte[] img;
    private Date creatData;
    private Set<ExchangeRate> exchangeRates = new HashSet<>(0);
    private Set<Transactions> transactionses = new HashSet<>(0);
    private Set<Accounts> accountses = new HashSet<>(0);

    public Valuta() {
    }

    public Valuta(int id) {
        this.id = id;
    }

    public Valuta(int id, String name, String shortName, byte[] img, Date creatData, Set<ExchangeRate> exchangeRates, Set<Transactions> transactionses, Set<Accounts> accountses) {
        this.id = id;
        this.name = name;
        this.shortName = shortName;
        this.img = img;
        this.creatData = creatData;
        this.exchangeRates = exchangeRates;
        this.transactionses = transactionses;
        this.accountses = accountses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "shortName")
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Column(name = "img")
    public byte[] getImg() {
        return this.img;
    }

    public void setImg(byte[] img) {
        this.img = img;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creatData", length = 23)
    public Date getCreatData() {
        return this.creatData;
    }

    public void setCreatData(Date creatData) {
        this.creatData = creatData;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "valuta")
    public Set<ExchangeRate> getExchangeRates() {
        return this.exchangeRates;
    }

    public void setExchangeRates(Set<ExchangeRate> exchangeRates) {
        this.exchangeRates = exchangeRates;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "valuta")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }

    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "valuta")
    public Set<Accounts> getAccountses() {
        return this.accountses;
    }

    public void setAccountses(Set<Accounts> accountses) {
        this.accountses = accountses;
    }

}
